#include "EventDrivenEngine.h"
#include <iostream>

// ==================================================
// CONSTRUCTOR
// ==================================================

EventDrivenEngine::EventDrivenEngine(
    int neuron_count
)
    : neurons(neuron_count),
      current_time(0.0),
      events_processed(0),
      spikes_generated(0) {
}


// ==================================================
// ADD EVENT
// ==================================================

void EventDrivenEngine::addEvent(
    const Event& event
) {

    eventQueue.push(event);

    // Record queue insertion
    monitor.recordQueueOperation();
}


// ==================================================
// ADD SYNAPSE
// ==================================================

void EventDrivenEngine::addSynapse(
    const Synapse& synapse
) {

    synapses.push_back(synapse);
}


// ==================================================
// RUN EVENT-DRIVEN SIMULATION
// ==================================================

void EventDrivenEngine::run(
    double end_time
) {

    while (!eventQueue.empty()) {

        // ----------------------------------------
        // Get earliest event
        // ----------------------------------------

        Event event =
            eventQueue.pop();

        // Record queue removal
        monitor.recordQueueOperation();


        // ----------------------------------------
        // Stop if event is beyond simulation time
        // ----------------------------------------

        if (event.time > end_time) {

            // The event has not been processed.
            // Put it back into the queue so that
            // simulation state is preserved.

            eventQueue.push(event);

            break;
        }


        // ----------------------------------------
        // Advance simulation clock
        // ----------------------------------------

        current_time =
            event.time;


        // ----------------------------------------
        // Record processed event
        // ----------------------------------------

        events_processed++;

        monitor.recordEvent();


        // ----------------------------------------
        // Check target neuron
        // ----------------------------------------

        if (
            event.target_neuron < 0 ||
            event.target_neuron >=
            static_cast<int>(neurons.size())
        ) {

            continue;
        }


        // ----------------------------------------
        // Get target neuron
        // ----------------------------------------

        Neuron& neuron =
            neurons[event.target_neuron];


        // ----------------------------------------
        // Event-driven neuron update
        // ----------------------------------------

        monitor.recordNeuronUpdate();


        // ----------------------------------------
        // Apply event weight
        // ----------------------------------------

        neuron.receiveInput(
            event.weight
        );


        // ----------------------------------------
        // Check whether neuron spikes
        // ----------------------------------------

        bool spike =
            neuron.update();


        if (spike) {

            spikes_generated++;

            monitor.recordSpike();


            std::cout
                << "Spike generated by Neuron "
                << event.target_neuron
                << " at time "
                << current_time
                << " ms\n";


            // ----------------------------------------
            // Propagate spike through synapses
            // ----------------------------------------

            for (
                const Synapse& synapse :
                synapses
            ) {

                if (
                    synapse.source_neuron ==
                    event.target_neuron
                ) {

                    Event newEvent;


                    // --------------------------------
                    // Synaptic delay
                    // --------------------------------

                    newEvent.time =
                        current_time +
                        synapse.delay;


                    // --------------------------------
                    // Destination neuron
                    // --------------------------------

                    newEvent.target_neuron =
                        synapse.target_neuron;


                    // --------------------------------
                    // Synaptic weight
                    // --------------------------------

                    newEvent.weight =
                        synapse.weight;


                    // --------------------------------
                    // Add future event to queue
                    // --------------------------------

                    eventQueue.push(
                        newEvent
                    );


                    // Record queue insertion
                    monitor.recordQueueOperation();


                    std::cout
                        << "  -> Event sent to Neuron "
                        << synapse.target_neuron
                        << " at time "
                        << newEvent.time
                        << " ms\n";
                }
            }
        }
    }


    // ----------------------------------------
    // Store observation time
    // ----------------------------------------

    monitor.setObservationTime(
        current_time
    );
}


// ==================================================
// GET SIMULATION STATE
// ==================================================

SimulationState
EventDrivenEngine::getState() const {

    SimulationState state;


    // ----------------------------------------
    // Current simulation time
    // ----------------------------------------

    state.current_time =
        current_time;


    // ----------------------------------------
    // Neuron membrane potentials
    // ----------------------------------------

    for (
        const Neuron& neuron :
        neurons
    ) {

        state.neuron_potentials.push_back(
            neuron.getPotential()
        );
    }


    // ----------------------------------------
    // Pending events
    // ----------------------------------------

    state.pending_events =
        eventQueue.getAllEvents();


    // ----------------------------------------
    // Simulation counters
    // ----------------------------------------

    state.spikes_generated =
        spikes_generated;

    state.events_processed =
        events_processed;

    state.neuron_updates =
        monitor.getNeuronUpdates();


    return state;
}


// ==================================================
// RESTORE SIMULATION STATE
// ==================================================

void EventDrivenEngine::setState(
    const SimulationState& state
) {

    // ----------------------------------------
    // Restore simulation time
    // ----------------------------------------

    current_time =
        state.current_time;


    // ----------------------------------------
    // Restore neuron membrane potentials
    // ----------------------------------------

    for (
        std::size_t i = 0;
        i < state.neuron_potentials.size() &&
        i < neurons.size();
        i++
    ) {

        neurons[i].setPotential(
            state.neuron_potentials[i]
        );
    }


    // ----------------------------------------
    // Restore pending events
    // ----------------------------------------

    eventQueue.setAllEvents(
        state.pending_events
    );


    // ----------------------------------------
    // Restore simulation counters
    // ----------------------------------------

    spikes_generated =
        state.spikes_generated;

    events_processed =
        state.events_processed;


    // ----------------------------------------
    // Restore neuron-update metric
    // ----------------------------------------

    monitor.setNeuronUpdates(
        state.neuron_updates
    );


    // ----------------------------------------
    // Restore observation time
    // ----------------------------------------

    monitor.setObservationTime(
        state.current_time
    );
}


// ==================================================
// GET EVENTS PROCESSED
// ==================================================

int
EventDrivenEngine::getEventsProcessed() const {

    return events_processed;
}


// ==================================================
// GET SPIKES GENERATED
// ==================================================

int
EventDrivenEngine::getSpikesGenerated() const {

    return spikes_generated;
}


// ==================================================
// GET CURRENT TIME
// ==================================================

double
EventDrivenEngine::getCurrentTime() const {

    return current_time;
}


// ==================================================
// GET SPIKE RATE
// ==================================================

double
EventDrivenEngine::getSpikeRate() const {

    return monitor.getSpikeRate();
}


// ==================================================
// GET NEURON UPDATES
// ==================================================

int
EventDrivenEngine::getNeuronUpdates() const {

    return monitor.getNeuronUpdates();
}


// ==================================================
// GET QUEUE OPERATIONS
// ==================================================

std::size_t
EventDrivenEngine::getQueueOperations() const {

    return monitor.getQueueOperations();
}