#include "TimeDrivenEngine.h"
#include <iostream>

// ==================================================
// CONSTRUCTOR
// ==================================================

TimeDrivenEngine::TimeDrivenEngine(
    int neuron_count,
    double dt
)
    : neurons(neuron_count),
      current_time(0.0),
      time_step(dt),
      neuron_updates(0),
      events_processed(0),
      spikes_generated(0) {
}


// ==================================================
// ADD SYNAPSE
// ==================================================

void TimeDrivenEngine::addSynapse(
    const Synapse& synapse
) {

    synapses.push_back(synapse);
}


// ==================================================
// ADD INPUT
// ==================================================

void TimeDrivenEngine::addInput(
    int neuron_id,
    double weight
) {

    if (
        neuron_id >= 0 &&
        neuron_id <
        static_cast<int>(neurons.size())
    ) {

        eventQueue.push({
            0.0,
            neuron_id,
            weight
        });
    }
}


// ==================================================
// ADD TIMESTAMPED EVENT
// ==================================================

void TimeDrivenEngine::addEvent(
    const Event& event
) {

    if (
        event.target_neuron >= 0 &&
        event.target_neuron <
        static_cast<int>(neurons.size())
    ) {

        eventQueue.push(
            event
        );
    }
}


// ==================================================
// RUN TIME-DRIVEN SIMULATION
// ==================================================

void TimeDrivenEngine::run(
    double end_time
) {

    while (
        current_time < end_time
    ) {

        // ----------------------------------------
        // Process events scheduled for this time
        // ----------------------------------------

        while (
            !eventQueue.empty()
        ) {

            Event event =
                eventQueue.pop();


            // ------------------------------------
            // Future event
            // ------------------------------------

            if (
                event.time > current_time
            ) {

                // Put the event back because it
                // belongs to a future timestep.

                eventQueue.push(
                    event
                );

                break;
            }


            // ------------------------------------
            // Validate target neuron
            // ------------------------------------

            if (
                event.target_neuron < 0 ||
                event.target_neuron >=
                static_cast<int>(
                    neurons.size()
                )
            ) {

                continue;
            }


            // ------------------------------------
            // Apply input
            // ------------------------------------

            neurons[event.target_neuron]
                .receiveInput(
                    event.weight
                );


            events_processed++;
        }


        // ----------------------------------------
        // Update EVERY neuron
        // ----------------------------------------

        for (
            int i = 0;
            i <
            static_cast<int>(
                neurons.size()
            );
            i++
        ) {

            neuron_updates++;


            bool spike =
                neurons[i].update();


            // ------------------------------------
            // Handle spike
            // ------------------------------------

            if (spike) {

                spikes_generated++;


                std::cout
                    << "Spike generated by Neuron "
                    << i
                    << " at time "
                    << current_time
                    << " ms\n";


                // --------------------------------
                // Schedule synaptic events
                // --------------------------------

                for (
                    const Synapse& synapse :
                    synapses
                ) {

                    if (
                        synapse.source_neuron ==
                        i
                    ) {

                        Event newEvent;


                        // Synaptic delay
                        newEvent.time =
                            current_time +
                            synapse.delay;


                        // Destination neuron
                        newEvent.target_neuron =
                            synapse.target_neuron;


                        // Synaptic weight
                        newEvent.weight =
                            synapse.weight;


                        // Add event
                        eventQueue.push(
                            newEvent
                        );


                        std::cout
                            << "  -> Event scheduled for Neuron "
                            << synapse.target_neuron
                            << " at time "
                            << newEvent.time
                            << " ms\n";
                    }
                }
            }
        }


        // ----------------------------------------
        // Move simulation forward
        // ----------------------------------------

        current_time +=
            time_step;
    }
}


// ==================================================
// GET SIMULATION STATE
// ==================================================

SimulationState
TimeDrivenEngine::getState() const {

    SimulationState state;


    // ----------------------------------------
    // Current simulation time
    // ----------------------------------------

    state.current_time =
        current_time;


    // ----------------------------------------
    // Save neuron potentials
    // ----------------------------------------

    for (
        const Neuron& neuron :
        neurons
    ) {

        state.neuron_potentials.push_back(
            neuron.getPotential()
        );
    }


    // ----------------------------------------
    // Save pending events
    // ----------------------------------------

    state.pending_events =
        eventQueue.getAllEvents();


    // ----------------------------------------
    // Save counters
    // ----------------------------------------

    state.spikes_generated =
        spikes_generated;

    state.events_processed =
        events_processed;

    state.neuron_updates =
        neuron_updates;


    return state;
}


// ==================================================
// RESTORE SIMULATION STATE
// ==================================================

void
TimeDrivenEngine::setState(
    const SimulationState& state
) {

    // ----------------------------------------
    // Restore simulation time
    // ----------------------------------------

    current_time =
        state.current_time;


    // ----------------------------------------
    // Restore neuron potentials
    // ----------------------------------------

    for (
        std::size_t i = 0;
        i < state.neuron_potentials.size() &&
        i < neurons.size();
        i++
    ) {

        neurons[i].setPotential(
            state.neuron_potentials[i]
        );
    }


    // ----------------------------------------
    // Restore pending events
    // ----------------------------------------

    eventQueue.setAllEvents(
        state.pending_events
    );


    // ----------------------------------------
    // Restore counters
    // ----------------------------------------

    spikes_generated =
        state.spikes_generated;

    events_processed =
        state.events_processed;


    // ----------------------------------------
    // Restore neuron-update metric
    // ----------------------------------------

    neuron_updates =
        state.neuron_updates;
}


// ==================================================
// GET NEURON UPDATES
// ==================================================

int
TimeDrivenEngine::getNeuronUpdates() const {

    return neuron_updates;
}


// ==================================================
// GET EVENTS PROCESSED
// ==================================================

int
TimeDrivenEngine::getEventsProcessed() const {

    return events_processed;
}


// ==================================================
// GET SPIKES GENERATED
// ==================================================

int
TimeDrivenEngine::getSpikesGenerated() const {

    return spikes_generated;
}


// ==================================================
// GET CURRENT TIME
// ==================================================

double
TimeDrivenEngine::getCurrentTime() const {

    return current_time;
}